name: weight_tracker
description: A modern Flutter app to track weight progress towards gaining 15kg in 6 months
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^12.1.3
  intl: ^0.20.2
  fl_chart: ^0.66.0
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
